# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/sushi/configuration/                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: NCPI-FHIR-Implementation-Guide
canonical: https://nih-ncpi.github.io/ncpi-fhir-ig
name: NCPIFHIRImplementationGuide
title: NCPI FHIR Implementation Guide
description: "FHIR Implementation Guide for the NIH Cloud Platform Interoperability Effort (NCPI)."
status: draft
license: CC0-1.0
version: 0.2.0
#fhirVersion: 4.0.1
fhirVersion: 4.3.0
copyrightYear: 2021+
releaseLabel: ci-build
publisher:
  name: NCPI FHIR Working Group
  url: https://github.com/nih-ncpi
contact:
  - name: Meen Chul Kim
    telecom:
      - system: email
        value: meenchul@d3b.center
        use: work
dependencies:
  hl7.fhir.us.core: 3.1.1

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  IG Home: index.html
  Table of Contents: toc.html
  Background:
    NCPI: ncpi.html
    Profile Versioning: ig_versioning.html
    FHIR Basics: FHIR_Basics.html
    Authors: authors.html
    Contact: contact.html
  Modules:
    Modular IG Overview: modular_ig.html
    Research Study: research_study.html
    Study Metadata: study_metadata.html
    Participant-level Data: participant.html
    Assays and File Data: files.html
    Generic Tabular Data: tabular.html
    Family Relationships: family.html
  Use Case Guides: 
    Finding a Research Study: finding_a_research_study.html
    Genomic Analysis: performing_a_genomic_analysis.html
    Rare Disease: rare_disease.html
    Childhood Cancer: childhood_cancer.html
    Using "Source" Data: use_case_tabular_data.html
    EHR Data: ehr.html
  Examples:
    Research Study Examples: example-research-study-baylor-cmg.html
    Metadata Examples: example_study_metadata.html
    Raw Data Examples: example_raw_data.html
    Example Resources: artifacts.html#example-example-instances
  Artifacts: 
    All Artifacts: artifacts.html
    Profiles: artifacts.html#structures-resource-profiles
    Code Systems: artifacts.html#terminology-code-systems
    Value Sets: artifacts.html#terminology-value-sets
    Extensions: artifacts.html#structures-extension-definitions
    Data Types: artifacts.html#structures-data-type-profiles
  Support: 
    FHIR Versions: fhir_version.html
    FHIR Spec: http://hl7.org/fhir/R4/index.html
    Downloads: downloads.html
